---
Name: 'silverstripejsmanager'
After: 'framework/*','cms/*', 'siteconfig/*'
---
#SiteConfig:
#  extensions:
#    - SiteJSExtension
Controller:
  extensions:
    - SiteJSControllerExtension
SiteJsConfig:
  extensions:
    - Versioned("Stage","Live")